//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.15 at 01:42:21 PM CDT 
//


package com.assigment.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="home" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="alternateAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressType", namespace = "http://www.example.org/Address/", propOrder = {
    "home",
    "alternateAddress"
})
public class AddressType {

    @XmlElement(required = true)
    protected String home;
    @XmlElement(required = true)
    protected String alternateAddress;

    
    public AddressType() {
		super();
	}

	public AddressType(String home, String alternateAddress) {
		super();
		this.home = home;
		this.alternateAddress = alternateAddress;
	}

	/**
     * Gets the value of the home property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHome() {
        return home;
    }

    /**
     * Sets the value of the home property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHome(String value) {
        this.home = value;
    }

    /**
     * Gets the value of the alternateAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternateAddress() {
        return alternateAddress;
    }

    /**
     * Sets the value of the alternateAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternateAddress(String value) {
        this.alternateAddress = value;
    }

	@Override
	public String toString() {
		return "AddressType [home=" + home + ", alternateAddress=" + alternateAddress + "]";
	}
    
    

}
