//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.15 at 01:42:21 PM CDT 
//


package com.assigment.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Contact complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Contact">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="homeNum" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="emergencyNum" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="alternateNum" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Contact", propOrder = {
    "homeNum",
    "emergencyNum",
    "alternateNum"
})
public class Contact {

    protected long homeNum;
    protected long emergencyNum;
    protected Long alternateNum;

    /**
     * Gets the value of the homeNum property.
     * 
     */
    public long getHomeNum() {
        return homeNum;
    }

    /**
     * Sets the value of the homeNum property.
     * 
     */
    public void setHomeNum(long value) {
        this.homeNum = value;
    }

    /**
     * Gets the value of the emergencyNum property.
     * 
     */
    public long getEmergencyNum() {
        return emergencyNum;
    }

    /**
     * Sets the value of the emergencyNum property.
     * 
     */
    public void setEmergencyNum(long value) {
        this.emergencyNum = value;
    }

    /**
     * Gets the value of the alternateNum property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAlternateNum() {
        return alternateNum;
    }

    /**
     * Sets the value of the alternateNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAlternateNum(Long value) {
        this.alternateNum = value;
    }

    
	public Contact() {
		super();
	}

	public Contact(long homeNum, long emergencyNum, Long alternateNum) {
		super();
		this.homeNum = homeNum;
		this.emergencyNum = emergencyNum;
		this.alternateNum = alternateNum;
	}

	@Override
	public String toString() {
		return "Contact [homeNum=" + homeNum + ", emergencyNum=" + emergencyNum + ", alternateNum=" + alternateNum
				+ "]";
	}

	
    
}
