//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.15 at 01:42:21 PM CDT 
//


package com.assigment.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Marks complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Marks">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Subject" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="Marks" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
 *         &lt;element name="MaxMarks" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Marks", namespace = "http://www.example.org/Marks", propOrder = {
    "subject",
    "marks",
    "maxMarks"
})
public class Marks {

    @XmlElement(name = "Subject", namespace = "http://www.example.org/Marks", required = true)
    protected List<String> subject;
    @XmlElement(name = "Marks", namespace = "http://www.example.org/Marks", type = Integer.class)
    protected List<Integer> marks;
    @XmlElement(name = "MaxMarks", namespace = "http://www.example.org/Marks")
    protected int maxMarks;

    
    public Marks() {
		super();
	}

	public Marks(List<String> subject, List<Integer> marks, int maxMarks) {
		super();
		this.subject = subject;
		this.marks = marks;
		this.maxMarks = maxMarks;
	}

	/**
     * Gets the value of the subject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSubject() {
        if (subject == null) {
            subject = new ArrayList<String>();
        }
        return this.subject;
    }

    /**
     * Gets the value of the marks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the marks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getMarks() {
        if (marks == null) {
            marks = new ArrayList<Integer>();
        }
        return this.marks;
    }

    /**
     * Gets the value of the maxMarks property.
     * 
     */
    public int getMaxMarks() {
        return maxMarks;
    }

    /**
     * Sets the value of the maxMarks property.
     * 
     */
    public void setMaxMarks(int value) {
        this.maxMarks = value;
    }

	@Override
	public String toString() {
		return "Marks [subject=" + subject + ", marks=" + marks + ", maxMarks=" + maxMarks + "]";
	}
    
    

}
